### ISSUE TITLE
Update Install.ps1 for full cmdlet names

### ISSUE THREAD

**Issue by michaeltlombardi** [pecigonzalo/Oh-My-Powershell#1]
Best practice for published modules, scripts, and functions is to expand all aliases. Install.ps1 seems to use quite a few aliases. I can update and submit a PR.

**Comment by pecigonzalo** [comment]
Sounds good, i was trying to mock something and then get to refactoring for best practices. If you can submit a PR with this that would be amazing, otherwise ill try and do it myself

Thanks again!

**Comment by pecigonzalo** [comment]
Closed on https://github.com/pecigonzalo/Oh-My-Powershell/commit/65ff03238520f7d2cc157005c5c1840775e746d4
