### ISSUE TITLE
Prompt for update, do not just update

### ISSUE THREAD

**Issue by pecigonzalo** [pecigonzalo/Oh-My-Powershell#19]

**Comment by leandrw** [comment]
Any work in progress? Can I help you?

**Comment by leandrocrs** [comment]
If you're interested, I put a small confirmation before each auto-update, asking user about the update.
https://github.com/leandrw/Oh-My-Powershell/commit/39f36ea19f14368f4398beba25bbd332585cdb3e.
Should be better if we can show each version, local and version of update, before update.

**Comment by pecigonzalo** [comment]
Is this part of your current PR? otherwise could you submit it? thanks!

**Comment by pecigonzalo** [comment]
Merge fixed this correct?

**Comment by leandrocrs** [comment]
yeap
