### ISSUE TITLE
Prompt don't break line after a command

### ISSUE THREAD

**Issue by leandrocrs** [pecigonzalo/Oh-My-Powershell#21]
Sometime the prompt line doesn't break the line, making the last command line fuzzy. 
![capture](https://cloud.githubusercontent.com/assets/1456009/14772445/ad45c482-0a74-11e6-9c15-b318a2f34f87.PNG)

This happens with every theme.

**Comment by pecigonzalo** [comment]
@leandrw thanks for the report and the PR. Can you past a screen on whats the output like after the change?

Also, what version of Powershell are you running? i dont get that with `ls` i think you are hitting something else. Is that PS `ls` or msys2/mingw/cygwin?

**Comment by leandrocrs** [comment]
Prints before and after line breaking. I forgot an detail: You need resize the window to "broke the line break". After my commit, you can resize window and line break will look normal.

![before](https://cloud.githubusercontent.com/assets/1456009/15000490/ad914d32-1166-11e6-9b66-c91d138aded3.PNG)
![after](https://cloud.githubusercontent.com/assets/1456009/15000491/ad9187c0-1166-11e6-950d-56038e8c1352.PNG)

**Comment by pecigonzalo** [comment]
This should be able to be closed after the merge
