### ISSUE TITLE
Oh-My-Powershell! needs a page!

### ISSUE THREAD

**Issue by leandrocrs** [pecigonzalo/Oh-My-Powershell#23]
Should be something amazing, clean and clever like [ohmyz.sh](http://ohmyz.sh). I used the Github Page Generator and made this http://leandrw.com.br/Oh-My-Powershell/, be it's not enough, but better than nothing.

**Comment by pecigonzalo** [comment]
Great idea!, Can you submit this as a PR? Thanks!

**Comment by leandrocrs** [comment]
I don't know how, but looks like you should create a `gh-pages` branch in your repo.

**Comment by pecigonzalo** [comment]
Oh ok, np, check how you did it in your site. thanks!

**Comment by leandrocrs** [comment]
Take a look at https://github.com/pecigonzalo/Oh-My-Powershell/settings

**Comment by pecigonzalo** [comment]
http://pecigonzalo.github.io/Oh-My-Powershel
