### ISSUE TITLE
Add Z to plugins 

### ISSUE THREAD

**Issue by afnpires** [pecigonzalo/Oh-My-Powershell#25]
Like oh-my-zsh, the Z plugin should be included.
There are 2 implementations in powershell of this.
https://github.com/vincpa/z
https://github.com/JannesMeyer/z.ps

**Comment by pecigonzalo** [comment]
Great idea! what if instead of just adding it here, we add support for adding get repos? By the looks if it, you can just install them as modules and then load them with OMP in the meantime.

**Comment by pecigonzalo** [comment]
I decided not to integrate this into the oh-my-posh as i think its well served by https://github.com/vincpa/z or https://github.com/JannesMeyer/z.ps

You will be able to load vincpa/z using

```
# User this section if you want to delegate module loading to Oh-My-Posh
$Modules = "z"
# Download modules if missing?
$Modules_Install = $true
```

Once i fix a issue with allowclober.

Thanks!
