### ISSUE TITLE
merging my power-theme into this repo

### ISSUE THREAD

**Issue by czhang03** [pecigonzalo/Oh-My-Powershell#26]
https://github.com/chantisnake/power-theme
here is my repo. 

But My repo requires `posh-git`... therefore... can I add it?

**Comment by pecigonzalo** [comment]
@chantisnake Yes of course, most of the current themes do, you can also put it as a "plugin" so you can remain owner of it under your own repo.
Let me know your thoughts

**Comment by czhang03** [comment]
moving them to https://github.com/JanJoris/oh-my-posh would be the first task for now.

I am sorry. I will try to add them to your repo if I have time
