### ISSUE TITLE
Updater munged files on name changes

### ISSUE THREAD

**Issue by keawade** [pecigonzalo/Oh-My-Powershell#28]
Taking an update this morning broke my installation. To fix it, I had to manually delete my .oh-my-powershell directory in `$env.USERPROFILE` and the oh-my-powershell directory in `$env.USERPROFILE\Documents\WindowsPowershell\Modules` as well as change the module import name in `$env.USERPROFILE\Documents\WindowsPowershell\Scripts\Microsoft.PowerShell_profile.ps1` from `Oh-My-Powershell` to `Oh-My-Posh` and reinstall. I finally had to restore my custom theme and the contents of my config file.

This replaced my directories with directories bearing the new module name and restored functionality.

**Comment by pecigonzalo** [comment]
@keawade as adviced on the release nodes

```
This a breaking release, as it changes the module name and config file name/location.
Please rename accordingly
```

The only changes required would be to change your profile to use the new module name and move any custom folder/files.

Im sorry for the inconveniance

**Comment by keawade** [comment]
I didn't go out of my way to update. The autoupdater prompted me asking if I wanted to update and I assumed it worked properly. There was no warning about the breaking release.

**Comment by pecigonzalo** [comment]
Ok, i understand, ill will leave this open and add some release message as a feature for the next release.

**Comment by leandrocrs** [comment]
Yeap! And we need do some fix in project's site and doc/README.
