### ISSUE TITLE
Library Integration and Standardized API to leverage global plugins

### ISSUE THREAD

**Issue by avdaredevil** [pecigonzalo/Oh-My-Powershell#30]
Hey @pecigonzalo,

One of the features that makes Oh-My-Zsh so great is it's open API, and extremely hackable design.

I've written a Polyfill-like library for PowerShell [[Components for PowerShell](https://github.com/avdaredevil/Components-For-Powershell)], which I feel would make for a great plugin within Oh-My-Posh. Let me know if you'd like to spec out a standardization/api for 3rd party integrations with other PS-Libraries.

Perhaps using npm/(some git client) as a method of automated installing of 3rd party/optional packages right from git!

**Comment by pecigonzalo** [comment]
@avdaredevil how are you?
Currently, the easiest way to install a library/module is using the PS Library and modules features of Powershell, that provides a standardized way of loading and distributing projects.
I feel adding npm or something like that might introduce an external dependency which might make things more complicated, but i certainly intended to support getting directly from git.

I think the easiest way is to configure `Components-For-Powershell` as a PowerShell module/library and be imported that way or if it had an entry point that imported the functions it could be added as a plugin.

Let me know your thoughts and what would be necessary from my side to ease the integration.

Thanks a lot!
