### ISSUE TITLE
Conflicting/inaccurate module name? (Should be "Oh-My-Powershell"?)

### ISSUE THREAD

**Issue by CollinChaffin** [pecigonzalo/Oh-My-Powershell#39]
I'm confused, your readme also lists "oh-my-posh" as the PSGallery install name, yet unless you're the same person as JanDeDobbeleer, why is that an almost identical module but much more updated, that not only also states the same "oh-my-posh" in the PSGallery, but that one and not this one is actually the one that is in the gallery?

But, when I go all the way past all of this to your website, there and ONLY there is the actual Gallery name listed as `"Oh-My-Powershell"`.

What's worse is neither is even listed as a fork.  This one really needs to be renamed ASAP to match the REAL active name of "Oh-My-Powershell", since it's not the one in the Gallery and is completely out of date if someone accidentally grabs this and installs it.

EDIT: I spoke too soon and now am even more confused.  I hadn't actually gone to confirm your website's name of "Oh-My-Powershell".  Now I find that is not actually valid, either.  So, everything seems inaccurate - your Github and your website.  Needs updating to avoid problems for folks.

**Comment by pecigonzalo** [comment]
@CollinChaffin which website are you talking about as "my website"? https://pecigonzalo.github.io/Oh-My-Posh ?

The project from JanDeDobbeleer it's only a theme engine, the scope of this project was to also include functionality, as in `oh-my-zsh`. Non of them are a fork of the other, so its not "out of date".

This project was named `oh-my-powershell` and it was requested by the users to be renamed to `oh-my-posh`. The `Import-Module "Oh-My-Powershell" -DisableNameChecking -NoClobber` line is probably wrong.
Please, I would ask you to tone done your message, you cant really "demand" I rename the project, but only suggest I do so. Feel free to submit a PR.
