### ISSUE TITLE
[Feature Request] History search is not scoped

### ISSUE THREAD

**Issue by colonelpopcorn** [pecigonzalo/Oh-My-Powershell#43]
First of all, this is really cool! PowerShell makes sense to use on Windows, but it's never really felt right. I love ohmyzsh on Mac, and a framework like this just makes sense. However, one of my favorite features of ohmyzsh seems to be missing. There doesn't seem to be a scoped history search. For example, when I type `git ` and then hit the up arrow key, I expect to only see the git commands I've used most recently in my history and not scroll through my whole history. Is this something that would be possible to implement in Oh-My-Posh?

**Comment by MartyGentillon** [comment]
This is more of a Readline feature.  And, in PSReadline, there are [various functions](https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-7.1#history-functions) already bound or that could be rebound to do this.  Specifically you have `HistorySearchBackward` and `HistorySearchForward` which are normally bound to `f8` and `shift+f8` respectively, though if you use emacs mode, they will be unbound.  They could be rebound in your configuration file using:

```
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
```

Also, you might consider using the i-search functions `ReverseSearchHistory` and `ForwardSearchHistory` and commands usually bound to `ctrl+r` and `ctrl+s` respectively.

**Comment by colonelpopcorn** [comment]
This configuration worked for me.
```powershell
Set-PSReadlineKeyHandler -Key UpArrow -Function HistorySearchBackward
Set-PSReadlineKeyHandler -Key DownArrow -Function HistorySearchForward
```
Thank you! This is really cool!
