### ISSUE TITLE
Add note that this shares the name of the most used project

### ISSUE THREAD

**Issue by fatso83** [pecigonzalo/Oh-My-Powershell#44]
Most people would assume that https://ohmyposh.dev/ is mapped by this project, given the name, but it seems it shares the name of https://github.com/jandedobbeleer/oh-my-posh, which is quite a lot more updated. Maybe it would be an idea to note this in the readme?

**Comment by pecigonzalo** [comment]
I believe its quite unfortunate that https://github.com/jandedobbeleer/oh-my-posh took that name, as it has no resemblance to `oh-my-zsh` or similar and AFAIR this project existed before. Ill add a note in the README.

Keep in mind the projects are quite differnt, as https://github.com/jandedobbeleer/oh-my-posh is just a theming tool.

**Comment by pecigonzalo** [comment]
https://github.com/pecigonzalo/Oh-My-Posh/commit/9ecef0aface94c0725b788aaf4d381966ce40efe
